name: Workflow-CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
permissions:
  contents: write
  
env:
  CSV_URL: "MLproject/used_car_price_dataset_extended_raw.csv"
  TARGET_VAR: "price_usd"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7 (sesuai rekomendasi submission)
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
 
      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run ./MLproject --env-manager=local 

      # Ambil run_id terbaru secara otomatis
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Install dependency yang digunakan dalam run tersebut
      # - name: Install Python Dependencies
      #   run: |
      #     REQ_TXT="mlruns/0/$RUN_ID/artifacts/model/requirements.txt"
      #     pip install $REQ_TXT

      # Save models to GitHub Repository
      - name: Upload to this GitHub Repository
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns/
          git commit -m "[Automated CI] Save mlruns"
          git push origin main

      # Buat Image Docker (build-docker)
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-ci-msml"

      # Log in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag workflow-ci-msml ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci-msml:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci-msml:latest   
